language: csharp

solution: MyStuff.sln

os: linux

mono: 
 - latest
 - 5.18.0
 - 3.12.0
 - 3.10.0

dotnent: 2.2

script:
  - msbuild /p:Configuration=Release solution-name.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
  - dotnet test SimpleTests

matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty    
    - dotnet: 2.0.0